#!/usr/bin/env bash
# Generate Toolchain/Rust/.cargo/config.toml for cross-compiling Rust to SerenityOS.
# Scans Toolchain/Rust/crates/ dynamically for [patch.crates-io] entries.
#
# Usage: bash Toolchain/Rust/generate-cargo-config.sh [TARGET_ARCH]
#   TARGET_ARCH: aarch64 (default), x86_64, or riscv64
#
# Called by BuildRust.sh and by Rust binary port build() functions.
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SERENITY_DIR="$(cd "${DIR}/../.." && pwd)"
TOOLCHAIN_BIN="${SERENITY_DIR}/Toolchain/Local/clang/bin"
RUST_DIR="${DIR}"

# Detect target architecture
if [ -n "${1:-}" ]; then
    TARGET_ARCH="$1"
elif [ -n "${SERENITY_ARCH:-}" ]; then
    TARGET_ARCH="${SERENITY_ARCH}"
elif [ -d "${SERENITY_DIR}/Build/aarch64clang/Root" ]; then
    TARGET_ARCH="aarch64"
elif [ -d "${SERENITY_DIR}/Build/x86_64clang/Root" ]; then
    TARGET_ARCH="x86_64"
elif [ -d "${SERENITY_DIR}/Build/riscv64clang/Root" ]; then
    TARGET_ARCH="riscv64"
else
    TARGET_ARCH="aarch64"
fi

case "${TARGET_ARCH}" in
    aarch64)
        SERENITY_TARGET="aarch64-unknown-serenity"
        LINKER="${TOOLCHAIN_BIN}/aarch64-serenity-clang"
        ;;
    x86_64)
        SERENITY_TARGET="x86_64-unknown-serenity"
        LINKER="${TOOLCHAIN_BIN}/x86_64-serenity-clang"
        ;;
    riscv64)
        SERENITY_TARGET="riscv64-unknown-serenity"
        LINKER="${TOOLCHAIN_BIN}/riscv64-serenity-clang"
        ;;
    *)
        echo "ERROR: Unsupported architecture: ${TARGET_ARCH}" >&2
        echo "       Supported: aarch64, x86_64, riscv64" >&2
        exit 1
        ;;
esac

# Resolve sysroot
if [ -n "${SERENITY_BUILD_DIR:-}" ]; then
    SYSROOT="${SERENITY_BUILD_DIR}/Root"
elif [ -d "${SERENITY_DIR}/Build/${TARGET_ARCH}clang/Root" ]; then
    SYSROOT="$(realpath "${SERENITY_DIR}/Build/${TARGET_ARCH}clang/Root")"
elif [ -d "${SERENITY_DIR}/Build/${TARGET_ARCH}/Root" ]; then
    SYSROOT="$(realpath "${SERENITY_DIR}/Build/${TARGET_ARCH}/Root")"
else
    echo "WARNING: Could not find SerenityOS build root for ${TARGET_ARCH}." >&2
    echo "         Set SERENITY_BUILD_DIR before running, or build SerenityOS first." >&2
    SYSROOT="/path/to/Build/${TARGET_ARCH}clang/Root"
fi

TOOLCHAIN_LIB="$(realpath "${SERENITY_DIR}/Toolchain/Local/clang/lib/${SERENITY_TARGET}")"
STUBS_DIR="$(realpath "${SERENITY_DIR}/Toolchain/Stubs/${TARGET_ARCH}")"
CRATES_DIR="${RUST_DIR}/crates"

# Build [patch.crates-io] by scanning installed crates
PATCH_ENTRIES=""
PATCH_COUNT=0
if [ -d "${CRATES_DIR}" ]; then
    for crate_dir in "${CRATES_DIR}"/*/; do
        [ -f "${crate_dir}/Cargo.toml" ] || continue
        crate_name="$(grep -m1 '^name = ' "${crate_dir}/Cargo.toml" | sed 's/name = "\(.*\)"/\1/')"
        [ -n "${crate_name}" ] || continue
        dir_name="$(basename "${crate_dir%/}")"
        if [ "${dir_name}" = "${crate_name}" ]; then
            PATCH_ENTRIES="${PATCH_ENTRIES}${crate_name} = { path = \"${crate_dir%/}\" }\n"
        else
            PATCH_ENTRIES="${PATCH_ENTRIES}${dir_name} = { package = \"${crate_name}\", path = \"${crate_dir%/}\" }\n"
        fi
        PATCH_COUNT=$((PATCH_COUNT + 1))
    done
fi

mkdir -p "${RUST_DIR}/.cargo"
{
    cat << EOF
# Cargo config for cross-compiling Rust to SerenityOS (${TARGET_ARCH}).
# Generated by Toolchain/Rust/generate-cargo-config.sh - do not edit manually.

[target.${SERENITY_TARGET}]
linker = "${LINKER}"
rustflags = [
    "-C", "link-arg=--sysroot=${SYSROOT}",
    "-C", "link-arg=-L${TOOLCHAIN_LIB}",
    "-C", "link-arg=-L${STUBS_DIR}",
    "-C", "link-arg=-lunwind",
]
EOF

    if [ -n "${PATCH_ENTRIES}" ]; then
        echo ""
        echo "[patch.crates-io]"
        printf '%b' "${PATCH_ENTRIES}"
    fi
} > "${RUST_DIR}/.cargo/config.toml"

echo "Generated ${RUST_DIR}/.cargo/config.toml (target: ${SERENITY_TARGET}, ${PATCH_COUNT} patched crate(s))"
